### ISSUE TITLE
Error while running theano mnist file.

### ISSUE THREAD

**Issue by leena1302** [mila-udem/blocks#1155]
Hi, I am trying to run the mnist file as suggested in the tutotrial, but unfortunately found these errors. I am trying to search for a solution but have not found it yet. please let me know how can this be fixed.

*********************Output************************

runfile('/Users/leena/Documents/lasagne/examples/mnist.py', wdir='/Users/leena/Documents/lasagne/examples')
Loading data...
Building model and compiling functions...
Traceback (most recent call last):

  File "<ipython-input-83-20ec403a3ab2>", line 1, in <module>
    runfile('/Users/leena/Documents/lasagne/examples/mnist.py', wdir='/Users/leena/Documents/lasagne/examples')

  File "/Users/leena/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "/Users/leena/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/leena/Documents/lasagne/examples/mnist.py", line 362, in <module>
    main(**kwargs)

  File "/Users/leena/Documents/lasagne/examples/mnist.py", line 284, in main
    train_fn = theano.function([input_var, target_var], loss, updates=updates)

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 1777, in orig_function

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 1644, in create

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/vm.py", line 1053, in make_all

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/op.py", line 924, in make_thunk

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/op.py", line 828, in make_c_thunk

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/cc.py", line 1578, in cthunk_factory

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/cc.py", line 1268, in cmodule_key

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/gof/cc.py", line 944, in compile_args

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/tensor/blas.py", line 501, in c_compile_args

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/tensor/blas.py", line 381, in ldflags

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/configparser.py", line 328, in __get__

  File "/Users/leena/anaconda/lib/python3.5/site-packages/theano/configdefaults.py", line 1258, in default_blas_ldflags

IndexError: ('The following error happened while compiling the node', Dot22(Reshape{2}.0, W), '\n', 'list index out of range')

**Comment by dmitriy-serdyuk** [comment]
As I can see, you are using [Lasagne](http://lasagne.readthedocs.io/en/latest/index.html). Please refer to their documentation how to contact the developers. I am not sure about the policy of Lasagne project, here we use the mail list for these kind of issues. I recommend you to check for the mailing list of Lasagne.

Feel free to reopen if I am wrong.
