### ISSUE TITLE
Optimization Failure

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#633]
Reproducible with `blocks/examples/mnist.py`

```
ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR:theano.gof.opt:Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/rizar/dist/fully-neural-lvsr/Theano/theano/gof/opt.py", line 1485, in process_node
    replacements = lopt.transform(node)
  File "/home/rizar/dist/fully-neural-lvsr/Theano/theano/sandbox/cuda/opt.py", line 503, in local_gpu_lazy_ifelse
    outs[i] = gpu_from_host(outs[i])
  File "/home/rizar/dist/fully-neural-lvsr/Theano/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/rizar/dist/fully-neural-lvsr/Theano/theano/sandbox/cuda/basic_ops.py", line 132, in make_node
    dtype=x.dtype)()])
  File "/home/rizar/dist/fully-neural-lvsr/Theano/theano/sandbox/cuda/type.py", line 70, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None
```

Can somebody please confirm this bug? Apparently it is related to https://github.com/bartvm/blocks/pull/595

**Comment by rizar** [comment]
Wow, seems like this is the one being fixed in #606! But I would have appreciated if you had posted this error message from the very beginning, @udibr.

@nouiz, I hope you can answer a question for me: what is the right `dtype` for a ratio of `int64` and `float32`? This investigation below shows, that now it will be `float64`. Is there a good motivation for it?

```
(Pdb) debugprint(x)
Elemwise{add,no_inplace} [@A] ''   
 |Elemwise{true_div,no_inplace} [@B] 'misclassificationrate_apply_error_rate'   
 | |Sum{acc_dtype=int64} [@C] ''   
 | | |Elemwise{neq,no_inplace} [@D] ''   
 | |   |Flatten{1} [@E] 'misclassificationrate_apply_y'   
 | |   | |targets [@F]
 | |   |MaxAndArgmax.1 [@G] 'argmax'   
 | |     |Elemwise{add,no_inplace} [@H] 'linear_1_apply_output'   
 | |     | |Dot22 [@I] ''   
 | |     | | |Elemwise{tanh,no_inplace} [@J] 'tanh_apply_output'   
 | |     | | | |Elemwise{add,no_inplace} [@K] 'linear_0_apply_output'   
 | |     | | |   |Dot22 [@L] ''   
 | |     | | |   | |Flatten{2} [@M] 'mlp_apply_args_0'   
 | |     | | |   | | |HostFromGpu [@N] 'features'   
 | |     | | |   | |   |GpuFromHost [@O] ''   
 | |     | | |   | |     |features [@P]
 | |     | | |   | |HostFromGpu [@Q] ''   
 | |     | | |   |   |W [@R]
 | |     | | |   |DimShuffle{x,0} [@S] ''   
 | |     | | |     |HostFromGpu [@T] ''   
 | |     | | |       |b [@U]
 | |     | | |HostFromGpu [@V] ''   
 | |     | |   |W [@W]
 | |     | |DimShuffle{x,0} [@X] ''   
 | |     |   |HostFromGpu [@Y] ''   
 | |     |     |b [@Z]
 | |     |TensorConstant{1} [@BA]
 | |Elemwise{Cast{float32}} [@BB] ''   
 |   |Prod{acc_dtype=int64} [@BC] ''   
 |     |MakeVector [@BD] ''   
 |       |Shape_i{0} [@BE] ''   
 |       | |targets [@F]
 |       |Shape_i{1} [@BF] ''   
 |         |targets [@F]
 |shared_misclassificationrate_apply_error_rate [@BG]
(Pdb) x.owner.inputs[0].dtype
'float64'
(Pdb) x.owner.inputs[1].dtype
'float64'
(Pdb) x.owner.inputs[0].owner
Elemwise{true_div,no_inplace}(Sum{acc_dtype=int64}.0, Elemwise{Cast{float32}}.0)
(Pdb) x.owner.inputs[0].owner.inputs[0]
Sum{acc_dtype=int64}.0
(Pdb) x.owner.inputs[0].owner.inputs[0].dtype
'int64'
(Pdb) x.owner.inputs[0].owner.inputs[1].dtype
'float32'
(Pdb) x.owner.inputs[0].dtype
'float64'
```

**Comment by nouiz** [comment]
All elemwise operation use the upcast of the c rules. C tell that int32
(and int64) with float32 give float64.

The reason is that you can't fit all int32 number in a float32. So to not
loose precission by default, the operation is upcasted to float64. To not
have the upcast, you should use int8 or int16

Fred

**Comment by rizar** [comment]
On a related note: for `tensor.mean` the default `acc_dtype` is `float64` even when `floatX=float32`. This, wrapped in an `theano.ifelse.ifelse` sometimes also causes an optimization failure similar to the one described in the top entry. The "sometimes" word means, that my simple example works, but my long programs crash.

@nouiz, any ideas what I should with it? The naive way is to find all `tensor.mean` calls and substitute `acc_dtype` with `floatX`, but this is somewhat tedious...

**Comment by rizar** [comment]
And thanks for the explanation about `int64`, `float64` and `float32`, that was really helpful!

**Comment by nouiz** [comment]
I do not understand the problem you have with mean. If have good default to
my knowledge:

>>> v=theano.tensor.fvector()
>>> v.mean().dtype
'float32'
>>> theano.printing.debugprint(v.mean(), print_type=True)
Elemwise{true_div,no_inplace} [@A] <TensorType(float32, scalar)> ''
 |Sum{acc_dtype=float64} [@B] <TensorType(float32, scalar)> ''
 | |<TensorType(float32, vector)> [@C] <TensorType(float32, vector)>
 |Subtensor{int64} [@D] <TensorType(float32, scalar)> ''
   |Elemwise{Cast{float32}} [@E] <TensorType(float32, vector)> ''
   | |Shape [@F] <TensorType(int64, vector)> ''
   |   |<TensorType(float32, vector)> [@C] <TensorType(float32, vector)>
   |Constant{0} [@G] <int64>

What is the input dtype of mean that cause you problem?

**Comment by rizar** [comment]
All right, never mind what I said about, `mean`, it was wrong. But the issue with `ifelse`, GPU and dtypes other than `float32` still exists. I paste a fragment of a pdb session that I entered by setting `on_opt_error=pdb` in THEANO_FLAGS:

```
(Pdb) n
ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR:theano.gof.opt:Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 1485, in process_node
    replacements = lopt.transform(node)
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py", line 503, in local_gpu_lazy_ifelse
    outs[i] = gpu_from_host(outs[i])
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 132, in make_node
    dtype=x.dtype)()])
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/type.py", line 70, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype int64 for variable None

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 1485, in process_node
    replacements = lopt.transform(node)
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py", line 503, in local_gpu_lazy_ifelse
    outs[i] = gpu_from_host(outs[i])
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 132, in make_node
    dtype=x.dtype)()])
  File "/home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/type.py", line 70, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype int64 for variable None

> /home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/type.py(70)__init__()
-> (self.__class__.__name__, dtype, name))
(Pdb) u
> /home/rizar/.local/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py(132)make_node()
-> dtype=x.dtype)()])
(Pdb) debugprint(x, depth=6)
*** NameError: name 'debugprint' is not defined
(Pdb) from theano.printing import debugprint
(Pdb) debugprint(x, depth=6)
Elemwise{add,no_inplace} [@A] ''   
 |Shape_i{1} [@B] 'batch_size'   
 | |features [@C]
 |shared_batch_size [@D]
```

I reopen the issue, because the reverse_words demo in still affected.

**Comment by rizar** [comment]
Localized the issue, https://github.com/Theano/Theano/issues/2913

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/2914
