### ISSUE TITLE
Failing tests, too high rtol

### ISSUE THREAD

**Issue by bartvm** [mila-udem/blocks#665]
Both fail on my desktop:

```
======================================================================
FAIL: test_many_steps (tests.bricks.test_recurrent.TestGatedRecurrent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vanmerb/lisa/blocks/tests/bricks/test_recurrent.py", line 277, in test_many_steps
    1e-05)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-05, atol=0

(mismatch 100.0%)
 x: array([[[  0.000000e+00,   0.000000e+00,   0.000000e+00],
        [  3.786875e-02,   3.786875e-02,   3.786875e-02],
        [  3.895702e-02,   3.895702e-02,   3.895702e-02],...
 y: array([[[  0.000000e+00,   0.000000e+00,   0.000000e+00],
        [  3.786876e-02,   3.786876e-02,   3.786876e-02],
        [  3.895702e-02,   3.895702e-02,   3.895702e-02],...

======================================================================
FAIL: tests.bricks.test_cost.FunctionTestCase (test_softmax_matrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vanmerb/lisa/blocks/tests/bricks/test_cost.py", line 59, in test_softmax_matrix
    assert_allclose(softmax_cost, softmax_cost_stable)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(1.0923779010772705, dtype=float32)
 y: array(1.092377781867981, dtype=float32)

----------------------------------------------------------------------
Ran 131 tests in 110.066s

FAILED (failures=2)
```

**Comment by dwf** [comment]
Think these are probably already resolved.
