### ISSUE TITLE
Error when I re-implement example for machine translation

### ISSUE THREAD

**Issue by xishazgh** [mila-udem/blocks#809]
Hi everyone,

 I get the following error:

Training status:
         batch_interrupt_received: False
         epoch_interrupt_received: False
         epoch_started: True
         epochs_done: 0
         iterations_done: 48
         received_first_batch: True
         resumed_from: f899e453ab7e4d66acbe7558d9dcedaf
         training_started: True
Log records from the iteration 48:
         decoder_cost_cost: 406.997089365

ERROR:blocks.main_loop:Error occured during training.

Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "__main__.py", line 45, in <module>
    get_dev_stream(**configuration), args.bokeh)
  File "../machine_translation/__init__.py", line 175, in main
    main_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.0.1-py2.7.egg/blocks/main_loop.py", line 196, in run
    reraise_as(e)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.0.1-py2.7.egg/blocks/utils/__init__.py", line 225, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.0.1-py2.7.egg/blocks/main_loop.py", line 182, in run
    while self._run_epoch():
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.0.1-py2.7.egg/blocks/main_loop.py", line 231, in _run_epoch
    while self._run_iteration():
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.0.1-py2.7.egg/blocks/main_loop.py", line 244, in _run_iteration
    batch = next(self.epoch_iterator)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 138, in get_data
    data = next(self.child_epoch_iterator)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 30, in __next__
    data = self.data_stream.get_data(next(self.request_iterator))
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 591, in get_data
    data, next(self.child_epoch_iterator)):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 639, in get_data
    return self.get_data()
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 633, in get_data
    data = next(self.child_epoch_iterator)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 214, in get_data
    data = next(self.child_epoch_iterator)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 30, in __next__
    data = self.data_stream.get_data(next(self.request_iterator))
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 591, in get_data
    data, next(self.child_epoch_iterator)):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/usr/local/lib/python2.7/dist-packages/fuel-0.0.1-py2.7-linux-x86_64.egg/fuel/transformers/__init__.py", line 215, in get_data
    image = self.mapping(data)
  File "../machine_translation/stream.py", line 83, in __call__
    for x in sentence_pair[0]],
IndexError: tuple index out of range

Original exception:
        IndexError: tuple index out of range

----------------------------------------------------------------------------------------------------------------------
the training data is download from WMT15 cs-en following prepare_data.py description.

Could anyone help me with it?

**Comment by rizar** [comment]
Which version of Blocks are you using?

Can you please open an issue in Blocks-examples repo instead?

**Comment by xishazgh** [comment]
ok . I move this issue at https://github.com/mila-udem/blocks-examples/issues/36
