### ISSUE TITLE
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> using Softmax brick

### ISSUE THREAD

**Issue by johnarevalo** [mila-udem/blocks#956]
[This](https://gist.github.com/johnarevalo/e2e46c79898639c57e65) is a `SimpleRecurrent` with `Softmax` on top. Running it with theano flag `floatX=float32` shows the mentioned error. When the `Softmax.categorical_cross_entropy` cost is replaced with `theano.tensor.nnet.categorical_crossentropy` (i.e. uncomment [line 60](https://gist.github.com/johnarevalo/e2e46c79898639c57e65#file-rnn_softmax-py-L60)), the error disappears.  In the generated plot you can see that both costs behave equal. I did not use `MainLoop` to isolate the error (that it is fired in the theano updates definition), however it also occurs using the full-Blocks approach (`GradientDescent`, `MainLoop`, etc)
The complete log is:

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle') local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_div_dimshuffle
ERROR (theano.gof.opt): node: Sum{axis=[1], acc_dtype=float64}(Elemwise{true_div,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/opt/anaconda/envs/masterenv/lib/python2.7/site-packages/theano/gof/fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[1], acc_dtype=float64}.0, Elemwise{true_div,no_inplace}.0, TensorType(float32, vector), TensorType(float64, vector), 'local_sum_prod_div_dimshuffle')
```

**Comment by johnarevalo** [comment]
My fault. It was because of `targets.dtype` was `'uint8'`. It requires at least `'int32'`. Do you think it would be useful to include such validation in `categorical_cross_entropy`?

**Comment by johnarevalo** [comment]
My fault. It was because `targets.dtype` was `'uint8'`. It requires at least `'int32'`.

**Comment by dmitriy-serdyuk** [comment]
@johnarevalo , is it solved? Strange, that it worked with pure theano.

**Comment by johnarevalo** [comment]
@dmitriy-serdyuk, the error message is displayed when `Softmax.categorical_cross_entropy` is used and `targets.dtype` is `uint8`. With `theano.tensor.nnet.categorical_crossentropy`, the error is not displayed. In both cases the cost diverges.

As workaround I modified the `targets.dtype` to `int32`. In this way, the error message is not displayed and the cost function converges (using the same script and params) for both `Softmax.categorical_cross_entropy` and `theano.tensor.nnet.categorical_crossentropy`. I did not close this issue because I find strange that an `int32` variable is required to store binary values.

**Comment by dmitriy-serdyuk** [comment]
The difference with theano is that we stabilize softmax [computation](https://github.com/mila-udem/blocks/blob/master/blocks/bricks/simple.py#L381). 

Theano always uses `int32` for integers/binaries and, furthermore, it is stored on gpu as `float32` at least with an old backend, I've heard that it was changed in the `gpuarray` backend. So this is a Theano or even hardware limitation.

I close this issue, feel free to reopen if you have more questions/ideas.
