### ISSUE TITLE
ProgressBar crashes when training reaches self.iter_count > 100

### ISSUE THREAD

**Issue by hsintone** [mila-udem/blocks#964]
I just removed and reinstalled my virtual environment and with it Theano, Fuel, Blocks, etc. Now I get this error when running my script:

```
  0 Traceback (most recent call last):
  1   File "/usr/lib64/python2.7/pdb.py", line 1314, in main
  2     pdb._runscript(mainpyfile)
  3   File "/usr/lib64/python2.7/pdb.py", line 1233, in _runscript
  4     self.run(statement)
  5   File "/usr/lib64/python2.7/bdb.py", line 400, in run
  6     exec cmd in globals, locals
  7   File "<string>", line 1, in <module>
  8   File "net.py", line 6, in <module>
  9     import logging
 10   File "net.py", line 239, in evaluate
 11     main_loop.run()
 12   File "~/di/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
 13     reraise_as(e)
 14   File "~/di/lib/python2.7/site-packages/blocks/utils/__init__.py", line 257, in reraise_as
 15     six.reraise(type(new_exc), new_exc, orig_exc_traceback)
 16   File "~/di/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
 17     while self._run_epoch():
 18   File "~/di/lib/python2.7/site-packages/blocks/main_loop.py", line 232, in _run_epoch
 19     while self._run_iteration():
 20   File "~/di/lib/python2.7/site-packages/blocks/main_loop.py", line 251, in _run_iteration
 21     self._run_extensions('before_batch', batch)
 22   File "~/di/lib/python2.7/site-packages/blocks/main_loop.py", line 263, in _run_extensions
 23     extension.dispatch(CallbackName(method_name), *args)
 24   File "~/di/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 67, in dispatch
 25     getattr(self, str(callback_name))(*args)
 26   File "~/di/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 505, in before_batch
 27     self.bar.update(self.iter_count)
 28   File "~/di/lib/python2.7/site-packages/progressbar/bar.py", line 444, in update
 29     % (self.min_value, self.max_value))
 30 ValueError: Value out of range, should be between 0 and 100

```
Here `self.iter_count` is 101, `self.min_value` is 0 and `self.max_value` is 100. So the crash occurs when my training reaches the 101th batch of my epoch. I simply have `Progressbar()` in my extension list that I pass to the main loop. It should display the `BouncingBar()`, as I have transformers that do not report the iteration scheme, but the bar itself looks like a growing row of hash characters (#) going from left to right, 0 to 100.

This error wasn't raised before, so now I'm wondering whether this is a recent bug, my mistake or a messed up installation. Any thoughts?

**Comment by vdumoulin** [comment]
It's due to the fact that `fuel` now requires `progressbar2==3.6.0`. The newer version deprecated the use of `maxval` in favour of `max_value` in the `ProgressBar` constructor. This is a simple change to make, I'll create a PR with the fix shortly.
